##################################################
  group:
    - group_name: "TestGroup2011"         
      vusers: '1'
      script_path: "paperino/test_http_request_wordpress_1" 
  scheduler:
     rampup: '45'
     duration: '20'
##################################################
