##################################################
  group:
    - group_name: "TestSLAThatIsPassed"
      vusers: '1'
      script_path: "scripts/TestProtocolloHTTP"
  scheduler:
     duration: '20'
  sla:
    transaction_res_time_percentile:
      percentile: '5'     
      transaction:
        - name: "Action_Transaction"
          threshold: '60'
        - name: "1_transaction"
          threshold: '60'
##################################################
