##################################################
  group:
    - group_name: "TestSLAPassed"
      vusers: '1'
      script_path: "demosla/WebHttpHtml1"
  scheduler:
     duration: '10'
  sla:
    transaction_res_time_percentile:
      percentile: '10' 
      transaction:
        - name: "Action_Transaction"
          threshold: '100'
        - name: "1_transaction"
          threshold: '11'
##################################################
