##################################################
  group:
    - group_name: "group_sla_failure"         
      vusers: '1'
      script_path: "demosla/test_http_request_wordpress_1" 
  scheduler:
     rampup: '45'
     duration: '20'
##################################################
