##################################################
  group:
    - group_name: "TestSLAFailed"
      vusers: '1'
      script_path: "demosla/WebHttpHtml1"
  scheduler:
     duration: '10'
  sla:
    transaction_res_time_percentile:
      percentile: '97'    
      transaction:
        - name: "Action_Transaction"
          threshold: '1'
        - name: "1_transaction"
          threshold: '1'
##################################################
