##################################################
  group:
    - group_name: "TestSLAFailed"
      vusers: '1'
      script_path: "demosla/WebHttpHtml1"
  scheduler:
     duration: '60'
  sla:
    transaction_res_time_percentile:
      percentile: '99'     
      transaction:
        - name: "Action_Transaction"
          threshold: '2'
        - name: "1_transaction"
          threshold: '2'
##################################################
